In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv('/Users/pavankumarbathula/Desktop/ml/survey_data_updated 5.csv')

In [5]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [6]:
pd.set_option('display.max_rows', None)
pd.DataFrame(df.dtypes, columns=['DataType'])

                               DataType
ResponseId                        int64
MainBranch                       object
Age                              object
Employment                       object
RemoteWork                       object
Check                            object
CodingActivities                 object
EdLevel                          object
LearnCode                        object
LearnCodeOnline                  object
TechDoc                          object
YearsCode                        object
YearsCodePro                     object
DevType                          object
OrgSize                          object
PurchaseInfluence                object
BuyNewTool                       object
BuildvsBuy                       object
TechEndorse                      object
Country                          object
Currency                         object
CompTotal                       float64
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
LanguageAdmired                  object
DatabaseHaveWorkedWith           object
DatabaseWantToWorkWith           object
DatabaseAdmired                  object
PlatformHaveWorkedWith           object
PlatformWantToWorkWith           object
PlatformAdmired                  object
WebframeHaveWorkedWith           object
WebframeWantToWorkWith           object
WebframeAdmired                  object
EmbeddedHaveWorkedWith           object
EmbeddedWantToWorkWith           object
EmbeddedAdmired                  object
MiscTechHaveWorkedWith           object
MiscTechWantToWorkWith           object
MiscTechAdmired                  object
ToolsTechHaveWorkedWith          object
ToolsTechWantToWorkWith          object
ToolsTechAdmired                 object
NEWCollabToolsHaveWorkedWith     object
NEWCollabToolsWantToWorkWith     object
NEWCollabToolsAdmired            object
OpSysPersonal use                object
OpSysProfessional use            object
OfficeStackAsyncHaveWorkedWith   object
OfficeStackAsyncWantToWorkWith   object
OfficeStackAsyncAdmired          object
OfficeStackSyncHaveWorkedWith    object
OfficeStackSyncWantToWorkWith    object
OfficeStackSyncAdmired           object
AISearchDevHaveWorkedWith        object
AISearchDevWantToWorkWith        object
AISearchDevAdmired               object
NEWSOSites                       object
SOVisitFreq                      object
SOAccount                        object
SOPartFreq                       object
SOHow                            object
SOComm                           object
AISelect                         object
AISent                           object
AIBen                            object
AIAcc                            object
AIComplex                        object
AIToolCurrently Using            object
AIToolInterested in Using        object
AIToolNot interested in Using    object
AINextMuch more integrated       object
AINextNo change                  object
AINextMore integrated            object
AINextLess integrated            object
AINextMuch less integrated       object
AIThreat                         object
AIEthics                         object
AIChallenges                     object
TBranch                          object
ICorPM                           object
WorkExp                         float64
Knowledge_1                      object
Knowledge_2                      object
Knowledge_3                      object
Knowledge_4                      object
Knowledge_5                      object
Knowledge_6                      object
Knowledge_7                      object
Knowledge_8                      object
Knowledge_9                      object
Frequency_1                      object
Frequency_2                      object
Frequency_3                      object
TimeSearching                    object
TimeAnswering                    object
Frustration                      object
ProfessionalTech                 object
ProfessionalCloud                object
ProfessionalQuestion             object
Industry                         object
JobSatPoints_1                  float64
JobSatPoints_4                  float64
JobSatPoints_5                  float64
JobSatPoints_6                  float64
JobSatPoints_7                  float64
JobSatPoints_8                  float64
JobSatPoints_9                  float64
JobSatPoints_10                 float64
JobSatPoints_11                 float64
SurveyLength                     object
SurveyEase                       object
ConvertedCompYearly             float64
JobSat                          float64

In [7]:
df=df.drop_duplicates()

In [8]:
df['Age_numeric']=df['Age'].replace({'35-44 years old':40, '45-54 years old':50, '25-34 years old':30,
       '55-64 years old':60, '18-24 years old':20, 'Under 18 years old':17,
       '65 years or older':66, 'Prefer not to say':np.nan})

/var/folders/q5/7kkw9h3x7hbc3myfclnvfswm0000gn/T/ipykernel_77521/3026373630.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age_numeric']=df['Age'].replace({'35-44 years old':40, '45-54 years old':50, '25-34 years old':30,

In [9]:
df['Age_numeric'].unique()

array([40., 50., 30., 60., 20., 17., 66., nan])

In [10]:
df=df.dropna(subset=['Age_numeric'])

In [11]:
tech_cols = {
    'LanguageHaveWorkedWith': 'Language',
    'DatabaseHaveWorkedWith': 'Database',
    'PlatformHaveWorkedWith': 'Platform',
    'WebframeHaveWorkedWith': 'WebFrame',
    'LanguageWantToWorkWith': 'Language',
    'DatabaseWantToWorkWith': 'Database',
    'PlatformWantToWorkWith': 'Platform',
    'WebframeWantToWorkWith': 'WebFrame'
}

for col, name in tech_cols.items():
    counts = (
        df[col]
        .dropna()
        .str.split(';')
        .explode()
        .value_counts()
        .reset_index()
    )

    counts.columns = [name, 'Count']
    counts.to_csv(f'{col}.csv', index=False)

print("Done!")

Done!

In [12]:
import os

[file for file in os.listdir() if file.endswith('.csv')]

['DatabaseWantToWorkWith.csv',
 'LanguageWantToWorkWith.csv',
 'PlatformWantToWorkWith.csv',
 'WebframeWantToWorkWith.csv',
 'PlatformHaveWorkedWith.csv',
 'WebframeHaveWorkedWith.csv',
 'LanguageHaveWorkedWith.csv',
 'DatabaseHaveWorkedWith.csv']

In [13]:
pd.read_csv('LanguageHaveWorkedWith.csv').head(10)

                  Language  Count
0               JavaScript  14923
1                      SQL  12585
2                 HTML/CSS  12392
3               TypeScript  10699
4                   Python   9580
5  Bash/Shell (all shells)   7237
6                       C#   6332
7                     Java   5974
8                      PHP   4637
9               PowerShell   3433

In [15]:
import shutil

files = [
    'LanguageHaveWorkedWith.csv',
    'DatabaseHaveWorkedWith.csv',
    'PlatformHaveWorkedWith.csv',
    'WebframeHaveWorkedWith.csv',
    'LanguageWantToWorkWith.csv',
    'DatabaseWantToWorkWith.csv',
    'PlatformWantToWorkWith.csv',
    'WebframeWantToWorkWith.csv'
]

for f in files:
    shutil.copy(f, '/Users/pavankumarbathula/Desktop/ml/')